name: remote ssh command
on: [push]
jobs:

  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/fantasylck
          git pull
          sudo systemctl restart fantasylck
